#!/bin/sh

#%# family=auto
#%# capabilities=autoconf suggest

ip=$(echo $0 | awk -F_ '{ print $2 }')
port=$(echo $0 | awk -F_ '{ print $3 }')

[ -z "$ip" ] && ip=127.0.0.1
[ -z "$port" ] && port=6379

if [ "$1" = "autoconf" ]; then
    redis-cli -h $ip -p $port info >/dev/null 2>&1 && echo yes && exit 0
    echo no
    exit 0
fi

if [ "$1" = "suggest" ]; then
    redis-cli -h $ip -p $port info >/dev/null 2>&1 && echo ${ip}_${port} && exit 0
fi

if [ "$1" = "config" ]; then
    # Expose all possibles graphes according to server's capabilities
    redis-cli -h $ip -p $port info | awk -F: '

    /^changes_since_last_save:/ { 
        print "multigraph redis_changes_since_last_save";
        print "graph_title Redis changes since last save" ;
        print "graph_info Number of write operations since last SAVE or BGSAVE";
        print "graph_category redis";
        print "changes.label changes";
    }; 

    /^keyspace_hits:/ {
        print "multigraph redis_commands";
        print "graph_order commands hits misses";
        print "graph_title Redis commands rate";
        print "graph_category redis";
        print "graph_vlabel commands/s";
        print "graph_info Redis commands per second";
        print "commands.label commands/s";
        print "commands.type COUNTER";
        print "commands.min 0";
        print "hits.label key hits";
        print "hits.type COUNTER";
        print "hits.min 0";
        print "misses.label key misses";
        print "misses.type COUNTER";
        print "misses.min 0";
    };

    /^total_connections_received:/ {
        print "multigraph redis_total_connections";
        print "graph_title Redis connections rate";
        print "graph_category redis";
        print "graph_vlabel connections/s";
        print "graph_info Connections per second to the Redis server";
        print "connections.label connections";
        print "connections.info connections per second";
        print "connections.type COUNTER";
        print "connections.min 0";
    };

    /^used_memory:/ {
        print "multigraph redis_memory";
        print "graph_title Redis memory usage";
        print "graph_category redis";
        print "graph_vlabel mem used";
        print "graph_info Memory allocated by Redis";
        print "graph_args --base 1024 -l 0";
        print "memory.label memory";
        print "memory.info Amount of mem used by Redis";
        print "memory.type GAUGE";
        print "memory.min 0";
    };

    /^connected_clients:/ {
        print "multigraph redis_clients";
        print "graph_title Redis connected clients";
        print "graph_category redis";
        print "graph_vlabel clients";
        print "graph_info Number of currently connected clients";
        print "clients.label clients";
        print "clients.type GAUGE";
        print "clients.min 0";
    };

    /^mem_fragmentation_ratio:/ {
        print "multigraph redis_fragmentation";
        print "graph_title Redis memory fragmentation";
        print "graph_category redis";
        print "graph_vlabel fragmentation ratio";
        print "graph_info Ratio between Redis RSS usage and allocated memory";
        print "frag.label fragmentation ratio";
        print "frag.type GAUGE";
        print "frag.min 0";
    };

    /^expired_keys:/ {
        print "multigraph redis_expired_keys";
        print "graph_title Redis expired keys rate";
        print "graph_category redis";
        print "graph_vlabel expired keys/s";
        print "graph_info Expired Redis keys per second";
        print "expired.label expired keys";
        print "expired.info expired keys per second";
        print "expired.type COUNTER";
        print "expired.min 0";
    };

    /^evicted_keys:/ {
        print "multigraph redis_evicted_keys";
        print "graph_title Redis evicted keys rate";
        print "graph_category redis";
        print "graph_vlabel evicted keys/s";
        print "graph_info Evicted Redis keys per second";
        print "evicted.label evicted keys";
        print "evicted.info evicted keys per second";
        print "evicted.type COUNTER";
        print "evicted.min 0";
    };

    /^pubsub_channels:/ {
        print "multigraph redis_pubsub_channels";
        print "graph_title Redis pubsub channels";
        print "graph_category redis";
        print "graph_vlabel channels";
        print "graph_info Number of pubsub channels";
        print "channels.label channels";
        print "channels.type GAUGE";
        print "channels.min 0";
    };

    /^blocked_clients:/ {
        print "multigraph redis_blocked_clients";
        print "graph_title Redis blocked clients";
        print "graph_category redis";
        print "graph_vlabel clients";
        print "graph_info Number of blocked clients";
        print "blocked.label clients";
        print "blocked.type GAUGE";
        print "blocked.min 0";
        print "blocked.warning 1";
    };

    /^db/ {
        split($2, where, "=|,");
        dbskeys[$1]    = where[2];
        dbsexpires[$1] = where[4];
    };
    
    END {
        print "multigraph redis_dbs";
        print "graph_title Redis dbs";
        print "graph_category redis";
        print "graph_vlabel keys";
        print "graph_info Number of keys per dbs";

        for (i in dbskeys)
            print i "keys.label " i " keys"
            print i "keys.type GAUGE"
            print i "keys.min 0"
            print i "expires.label " i " expired keys"
            print i "expires.type GAUGE"
            print i "expires.min 0";
    };

    '
    exit $?
fi

redis-cli -h $ip -p $port info | awk -F: '

    /^changes_since_last_save:/ {
        print "multigraph redis_changes_since_last_save";
        print "changes.value " $2 ;
    }; 

    /^total_connections_received:/ {
        print "multigraph redis_total_connections";
        print "connections.value " $2 ;
    }; 

    /^used_memory:/ {
        print "multigraph redis_memory";
        print "memory.value " $2 ;
    }; 

    /^connected_clients:/ {
        print "multigraph redis_clients";
        print "clients.value " $2 ;
    }; 

    /^mem_fragmentation_ratio:/ {
        print "multigraph redis_fragmentation";
        print "frag.value " $2 ;
    };

    /^expired_keys:/ {
        print "multigraph redis_expired_keys";
        print "expired.value " $2 ;
    };

    /^evicted_keys:/ {
        print "multigraph redis_evicted_keys";
        print "evicted.value " $2 ;
    };

    /^pubsub_channels:/ {
        print "multigraph redis_pubsub_channels";
        print "channels.value " $2 ;
    };

    /^blocked_clients:/ {
        print "multigraph redis_blocked_clients";
        print "blocked.value " $2 ;
    }; 

    /^total_commands_processed:/ {
        commands=$2
    }; 

    /^keyspace_hits:/ {
        hits=$2
    }; 

    /^keyspace_misses:/ {
        misses=$2
    }; 

    /^db/ {
        split($2, where, "=|,");
        dbskeys[$1]    = where[2];
	dbsexpires[$1] = where[4];
    };

    END {
        print "multigraph redis_commands";
        print "commands.value " commands;
        print "hits.value " hits;
        print "misses.value " misses;

        print "multigraph redis_dbs";
        for (i in dbskeys)
            print i "keys.value "    dbskeys[i]
            print i "expires.value " dbsexpires[i];
    };
'

